FROM debian:bullseye

EXPOSE 3306

COPY ./tools/mariadb_init.sh /mariadb_init.sh

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y mariadb-server \
	vim \
	mariadb-client \
	dumb-init \
	sudo && \
    mkdir -p /var/run/mysqld && \
    chown -R mysql:mysql /var/run/mysqld && \
    chmod +x mariadb_init.sh && \
    rm -f /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

ENTRYPOINT ["dumb-init", "--", "/mariadb_init.sh" ]