FROM debian:bullseye

EXPOSE 443

COPY ./tools/nginx_init.sh /nginx_init.sh

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y nginx openssl \
	dumb-init && \
    mkdir -p /etc/ssl && \
    chmod +x nginx_init.sh

COPY ./conf/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["dumb-init", "--", "/nginx_init.sh"]